with-expecter: true
inpackage: false
keeptree: false

name: Shortener

# где искать интерфейс (filesystem path)
dir: internal/transport/http/shortenerhandler

# куда класть сгенерированный mock
output: internal/transport/http/shortenerhandler/mocks

# имя пакета в сгенерированном файле
outpkg: mocks

filename: shortener_mock.go
