// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID       int32            `json:"id"`
	Url      string           `json:"url"`
	Alias    string           `json:"alias"`
	ExpireAt pgtype.Timestamp `json:"expire_at"`
}
