// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteURL = `-- name: DeleteURL :execrows
DELETE from url
WHERE alias = $1
`

func (q *Queries) DeleteURL(ctx context.Context, alias string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteURL, alias)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getURL = `-- name: GetURL :one
SELECT url FROM url
WHERE alias = $1
AND (expire_at IS NULL OR expire_at > now())
`

func (q *Queries) GetURL(ctx context.Context, alias string) (string, error) {
	row := q.db.QueryRow(ctx, getURL, alias)
	var url string
	err := row.Scan(&url)
	return url, err
}

const saveURL = `-- name: SaveURL :one
INSERT INTO url (url, alias, expire_at)
VALUES ($1, $2, $3)
RETURNING id
`

type SaveURLParams struct {
	Url      string           `json:"url"`
	Alias    string           `json:"alias"`
	ExpireAt pgtype.Timestamp `json:"expire_at"`
}

func (q *Queries) SaveURL(ctx context.Context, arg SaveURLParams) (int32, error) {
	row := q.db.QueryRow(ctx, saveURL, arg.Url, arg.Alias, arg.ExpireAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}
