{
 "title": "custom dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP latency p95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(url_shortener_http_request_duration_seconds_bucket[5m])) by (le)\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP status codes by minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(url_shortener_http_requests_total[1m])) by (status) * 60\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(url_shortener_http_requests_total[1m]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"url-shortener\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}