// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Shortener is an autogenerated mock type for the Shortener type
type Shortener struct {
	mock.Mock
}

type Shortener_Expecter struct {
	mock *mock.Mock
}

func (_m *Shortener) EXPECT() *Shortener_Expecter {
	return &Shortener_Expecter{mock: &_m.Mock}
}

// SaveURL provides a mock function with given fields: ctx, url, alias
func (_m *Shortener) SaveURL(ctx context.Context, url string, alias string) (int32, string, error) {
	ret := _m.Called(ctx, url, alias)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 int32
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int32, string, error)); ok {
		return rf(ctx, url, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int32); ok {
		r0 = rf(ctx, url, alias)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, url, alias)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, url, alias)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Shortener_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type Shortener_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - alias string
func (_e *Shortener_Expecter) SaveURL(ctx interface{}, url interface{}, alias interface{}) *Shortener_SaveURL_Call {
	return &Shortener_SaveURL_Call{Call: _e.mock.On("SaveURL", ctx, url, alias)}
}

func (_c *Shortener_SaveURL_Call) Run(run func(ctx context.Context, url string, alias string)) *Shortener_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Shortener_SaveURL_Call) Return(_a0 int32, _a1 string, _a2 error) *Shortener_SaveURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Shortener_SaveURL_Call) RunAndReturn(run func(context.Context, string, string) (int32, string, error)) *Shortener_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortener creates a new instance of Shortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Shortener {
	mock := &Shortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
