// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Shortener is an autogenerated mock type for the Shortener type
type Shortener struct {
	mock.Mock
}

type Shortener_Expecter struct {
	mock *mock.Mock
}

func (_m *Shortener) EXPECT() *Shortener_Expecter {
	return &Shortener_Expecter{mock: &_m.Mock}
}

// DeleteURL provides a mock function with given fields: ctx, alias
func (_m *Shortener) DeleteURL(ctx context.Context, alias string) error {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shortener_DeleteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURL'
type Shortener_DeleteURL_Call struct {
	*mock.Call
}

// DeleteURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *Shortener_Expecter) DeleteURL(ctx interface{}, alias interface{}) *Shortener_DeleteURL_Call {
	return &Shortener_DeleteURL_Call{Call: _e.mock.On("DeleteURL", ctx, alias)}
}

func (_c *Shortener_DeleteURL_Call) Run(run func(ctx context.Context, alias string)) *Shortener_DeleteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Shortener_DeleteURL_Call) Return(_a0 error) *Shortener_DeleteURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Shortener_DeleteURL_Call) RunAndReturn(run func(context.Context, string) error) *Shortener_DeleteURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function with given fields: ctx, alias
func (_m *Shortener) GetURL(ctx context.Context, alias string) (string, error) {
	ret := _m.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shortener_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type Shortener_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *Shortener_Expecter) GetURL(ctx interface{}, alias interface{}) *Shortener_GetURL_Call {
	return &Shortener_GetURL_Call{Call: _e.mock.On("GetURL", ctx, alias)}
}

func (_c *Shortener_GetURL_Call) Run(run func(ctx context.Context, alias string)) *Shortener_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Shortener_GetURL_Call) Return(_a0 string, _a1 error) *Shortener_GetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Shortener_GetURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Shortener_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveURL provides a mock function with given fields: ctx, url, alias, expireAt
func (_m *Shortener) SaveURL(ctx context.Context, url string, alias string, expireAt *time.Time) (int32, string, error) {
	ret := _m.Called(ctx, url, alias, expireAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 int32
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) (int32, string, error)); ok {
		return rf(ctx, url, alias, expireAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) int32); ok {
		r0 = rf(ctx, url, alias, expireAt)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *time.Time) string); ok {
		r1 = rf(ctx, url, alias, expireAt)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *time.Time) error); ok {
		r2 = rf(ctx, url, alias, expireAt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Shortener_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type Shortener_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - alias string
//   - expireAt *time.Time
func (_e *Shortener_Expecter) SaveURL(ctx interface{}, url interface{}, alias interface{}, expireAt interface{}) *Shortener_SaveURL_Call {
	return &Shortener_SaveURL_Call{Call: _e.mock.On("SaveURL", ctx, url, alias, expireAt)}
}

func (_c *Shortener_SaveURL_Call) Run(run func(ctx context.Context, url string, alias string, expireAt *time.Time)) *Shortener_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*time.Time))
	})
	return _c
}

func (_c *Shortener_SaveURL_Call) Return(_a0 int32, _a1 string, _a2 error) *Shortener_SaveURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Shortener_SaveURL_Call) RunAndReturn(run func(context.Context, string, string, *time.Time) (int32, string, error)) *Shortener_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewShortener creates a new instance of Shortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Shortener {
	mock := &Shortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
