// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shortenerhandler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShortener creates a new instance of MockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortener {
	mock := &MockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortener is an autogenerated mock type for the Shortener type
type MockShortener struct {
	mock.Mock
}

type MockShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortener) EXPECT() *MockShortener_Expecter {
	return &MockShortener_Expecter{mock: &_m.Mock}
}

// URLSave provides a mock function for the type MockShortener
func (_mock *MockShortener) URLSave(ctx context.Context, url string, alias string) (int32, string, error) {
	ret := _mock.Called(ctx, url, alias)

	if len(ret) == 0 {
		panic("no return value specified for URLSave")
	}

	var r0 int32
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int32, string, error)); ok {
		return returnFunc(ctx, url, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int32); ok {
		r0 = returnFunc(ctx, url, alias)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, url, alias)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, url, alias)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShortener_URLSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URLSave'
type MockShortener_URLSave_Call struct {
	*mock.Call
}

// URLSave is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - alias string
func (_e *MockShortener_Expecter) URLSave(ctx interface{}, url interface{}, alias interface{}) *MockShortener_URLSave_Call {
	return &MockShortener_URLSave_Call{Call: _e.mock.On("URLSave", ctx, url, alias)}
}

func (_c *MockShortener_URLSave_Call) Run(run func(ctx context.Context, url string, alias string)) *MockShortener_URLSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortener_URLSave_Call) Return(n int32, s string, err error) *MockShortener_URLSave_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *MockShortener_URLSave_Call) RunAndReturn(run func(ctx context.Context, url string, alias string) (int32, string, error)) *MockShortener_URLSave_Call {
	_c.Call.Return(run)
	return _c
}
